### ISSUE TITLE
Mod Meteor Defense Laser crashes with Automation Innovation pack

### ISSUE THREAD

**Issue by Storm-Engineer** [rlane/rlane-oni-mods#10]
The mod Meteor Defense Laser crashes since the Automation Innovation patch went live.
I've seen you posted on the Steam workshop stating you fixed it but it still crashes.

**Comment by rlane** [comment]
This is likely the same issue as https://forums.kleientertainment.com/forums/topic/114168-right-way-to-get-steam-to-support-versioned-updates/. You can try unsubscribing and resubscribing but there doesn't seem to be a reliable way to get Steam to download new versions of mods. I committed d3b6db6 in an attempt to fix this.
